[0m11:28:50.731680 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1085080c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1085eddb40>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1085eddae0>]}


============================== 11:28:50.736016 | c7caa1e6-3351-4609-b7ad-9bdc1d5da63d ==============================
[0m11:28:50.736016 [info ] [MainThread]: Running with dbt=1.9.2
[0m11:28:50.736728 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'fail_fast': 'False', 'profiles_dir': '/home/ricky/.dbt', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'log_format': 'default', 'static_parser': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m11:29:00.969520 [debug] [MainThread]: Starter project path: /home/ricky/git/medicare-analytics/dbt/venv/lib/python3.10/site-packages/dbt/include/starter_project
[0m11:29:00.974544 [info ] [MainThread]: 
Your new dbt project "medicare_analytics_dbt" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m11:29:00.975023 [info ] [MainThread]: Setting up your profile.
[0m11:29:00.976454 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m11:29:00.977524 [debug] [MainThread]: Resource report: {"command_name": "init", "command_success": false, "command_wall_clock_time": 10.30915, "process_in_blocks": "31608", "process_kernel_time": 0.114078, "process_mem_max_rss": "86720", "process_out_blocks": "64", "process_user_time": 1.482216}
[0m11:29:00.977935 [debug] [MainThread]: Command `dbt init` failed at 11:29:00.977845 after 10.31 seconds
[0m11:29:00.978279 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1085080c10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1085ede350>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f1085edea40>]}
[0m11:29:00.978693 [debug] [MainThread]: Flushing usage events
[0m11:29:01.281607 [debug] [MainThread]: An error was encountered while trying to flush usage events
